---

- name: upate apt cache
  apt:
    update_cache: yes
  ignore_errors: yes
  changed_when: False

- name: install requirements
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "apt-transport-https"
    - "ca-certificates"

- name: add repo key
  apt_key:
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    id: "58118E89F3A912897C070ADBF76221572C52609D"

- name: add docker engine repo
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
    state: "present"
    filename: docker-repo
    update_cache: yes

- name: install docker-engine
  apt:
    name: "docker-engine"
    state: present

- name: add directory for configuration overrides
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: "directory"
    mode: "0755"

