---

- name: install apt requirements
  apt:
    pkg: aptitude

- name: upgrade system
  apt:
    upgrade: full
    update_cache: yes

- name: add kernel extras
  apt:
    name: "linux-image-extra-{{ ansible_kernel }}"
    state: present

