---

- name: install apt requirements
  apt:
    pkg: aptitude
    state: present

- name: upgrade system
  apt:
    upgrade: yes

- name: add kernel extras
  apt:
    name: "linux-image-extra-{{ ansible_kernel }}"
    state: present

