---

- name: instal nginx and necessary packages
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "nginx"
    - "php-fpm"
    - "php-mysql"
    - "mariadb-server"

- name: create site dir
  file:
    path: "/opt/www"
    mode: 644
    owner: "root"
    group: "root"
    state: "directory"




